"""change relationship of notification

Revision ID: 27456f85571a
Revises: e50295cc9558
Create Date: 2025-03-13 21:11:41.107983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27456f85571a'
down_revision: Union[str, None] = 'e50295cc9558'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
           'fk_notification_user',  # Constraint name
           'notifications',         # Source table
           'users',                 # Referenced table
           ['user_id'],             # Source columns
           ['id']                   # Referenced columns
       )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_user_id', 'notifications', type_='foreignkey')
    # ### end Alembic commands ###
